---
metadata:
  name: "oes-analysisqas"
apiVersion: "argoproj.io/v1alpha1"
kind: "AnalysisTemplate"
spec:
  args:
  - name: "experiment-hash"
  metrics:
  - provider:
      opsmx:
        canaryStartTime: "2021-11-03T11:29:46.915Z"
        application: "argoappqatestnpqfr"
        profile: "opsmx-profile"
        lifetimeMinutes: 6
        threshold:
          pass: 80
          marginal: 60
        services:
        - logTemplateName: "qatestarfku"
          metricTemplateName: "metricTemplate7428"
          metricScopeVariables: "variable1"
          canaryLogScope: "canaryapp-rest-1"
          canaryMetricScope: "service:canaryapp"
          logScopeVariables: "kubernetes.container_name"
          baselineLogScope: "baseapp-rest-1"
          baselineMetricScope: "service:baseapp"
        gateUrl: "https://isd-argocd.isd-dev.opsmx.net/gate/"
        baselineStartTime: "2021-11-03T11:29:46.915Z"
        user: "user2"
    name: "oes-analysisqas"
